(()=>{
const KEY='the_eighty_v2_state';
const categories=['Personal','Professional','Spiritual','Fitness','Mental'];
const defaultGoals={
Personal:{name:'Intentional present time',target:'20 minutes present and intentional',minimum:'10 minutes fully present'},
Professional:{name:'Top 3 + shutdown routine',target:'Set Top 3 and complete shutdown routine',minimum:"Write tomorrow’s #1 priority"},
Spiritual:{name:'Spiritual connection',target:'10 minutes prayer, Bible, devotional, or reflection',minimum:'2 minutes prayer or reflection'},
Fitness:{name:'Walk / run mileage',target:'3.2 miles walking or running',minimum:'10-minute intentional walk'},
Mental:{name:'Intentional reset',target:'10-minute mental reset',minimum:'2 quiet minutes without the phone'}
};
const reasons=['Work ran late','Low energy','Family responsibility','Forgot','Goal felt too hard','Outside my control'];
let state=load();let selectedDay=1;let mode='path';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function load(){try{return Object.assign({goals:defaultGoals,days:{},miles:{},why:{},reviews:{}},JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return {goals:defaultGoals,days:{},miles:{},why:{},reviews:{}}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function dateKey(day=selectedDay){return `2026-10-${String(day).padStart(2,'0')}`}
function ensureDay(day=selectedDay){const k=dateKey(day);if(!state.days[k])state.days[k]={};return state.days[k]}
function colorFor(p){if(p<=50)return '#c62828';if(p<=64)return '#c2410c';if(p<=79)return '#d6a600';return '#16803d'}
function labelFor(p){if(p===100)return'Perfect';if(p>=80)return'Consistently Successful';if(p>=65)return'Needs Attention';if(p>=51)return'Rebuild';return p===0?'Ready':'Inconsistent'}
function calcDay(day=selectedDay){const d=ensureDay(day);let total=0,den=0;for(const c of categories){const v=d[c];if(v==='outside')continue;den++;total+=v==='target'?100:v==='minimum'?80:0}return den?Math.round(total/den):0}
function calcCategory(cat){let total=0,den=0;for(let day=1;day<=31;day++){const v=state.days[dateKey(day)]?.[cat];if(v==='outside')continue;if(v){den++;total+=v==='target'?100:v==='minimum'?80:0}}return den?Math.round(total/den):0}
function calcOverall(){const vals=categories.map(calcCategory).filter(v=>v>0);return vals.length?Math.round(vals.reduce((a,b)=>a+b,0)/vals.length):0}
function coachLine(p){if(p===0)return'Start with one intentional win.';if(p<51)return'Build some momentum. One win changes the direction.';if(p<80)return'The 80 is right there. Do the next right thing.';if(p<100)return'You earned the 80. Keep going if you’ve got more.';return'Complete day. You did what you said you would do.'}
function renderHome(){const p=calcDay();$('#overallScoreValue').textContent=p+'%';$('#overallScoreLabel').textContent=labelFor(p);$('#overallBar').style.width=p+'%';$('#overallScoreValue').style.color=p>=80?'#fff':'#fff';$('#heroCoach').textContent=coachLine(p);$('#todayScoreChip').textContent='Today '+p+'%';$('#todayScoreChip').style.color=colorFor(p);const dt=new Date(Date.UTC(2026,9,selectedDay));$('#selectedDateLabel').textContent=dt.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',timeZone:'UTC'});$('#dayNumberLabel').textContent=`DAY ${selectedDay} OF 31`;
 const wrap=$('#dailyTasks');wrap.innerHTML='';const day=ensureDay();
 categories.forEach(cat=>{const g=state.goals[cat]||defaultGoals[cat];const card=document.createElement('div');card.className='task-card';card.innerHTML=`<div class="eyebrow">${cat}</div><h3>${esc(g.name)}</h3><div class="goal-line"><span class="target-label">Target:</span> ${esc(g.target)}</div><div class="goal-line"><span class="minimum-label">Minimum:</span> ${esc(g.minimum)}</div><div class="task-actions"><button class="target-btn">✓ Target</button><button class="min-btn">+ Minimum</button><button class="why-btn">Why?</button></div><div class="why-panel hidden"><strong>What affected this commitment?</strong><div class="why-options"></div></div>`;
 const [tb,mb,wb]=card.querySelectorAll('.task-actions button'); if(day[cat]==='target')tb.classList.add('selected');if(day[cat]==='minimum')mb.classList.add('selected');
 tb.onclick=()=>{day[cat]=day[cat]==='target'?null:'target';save();renderAll()};mb.onclick=()=>{day[cat]=day[cat]==='minimum'?null:'minimum';save();renderAll()};const panel=card.querySelector('.why-panel');wb.onclick=()=>panel.classList.toggle('hidden');
 const whyWrap=card.querySelector('.why-options');reasons.forEach(r=>{const b=document.createElement('button');b.type='button';b.textContent=r;const k=dateKey();const sel=(state.why[k]?.[cat]||[]).includes(r);if(sel)b.classList.add('selected');b.onclick=()=>{state.why[k]??={};state.why[k][cat]??=[];const arr=state.why[k][cat];const i=arr.indexOf(r);if(i>=0)arr.splice(i,1);else arr.push(r);if(r==='Outside my control' && i<0)day[cat]='outside';save();renderAll()};whyWrap.appendChild(b)});wrap.appendChild(card)});renderMiles()}
function renderMiles(){const vals=Object.values(state.miles).map(Number);const total=vals.reduce((a,b)=>a+b,0);$('#milesTotal').textContent=total.toFixed(1);$('#milesRemaining').textContent=Math.max(0,100-total).toFixed(1)+' mi';$('#milesProgress').style.width=Math.min(100,total)+'%';const daysLeft=Math.max(1,32-selectedDay);$('#milesPace').textContent=(Math.max(0,100-total)/daysLeft).toFixed(2)+'/day';const target=100*selectedDay/31;const diff=total-target;$('#paceStatus').textContent=diff>=0?`${diff.toFixed(1)} mi ahead`:`${Math.abs(diff).toFixed(1)} mi behind`;$('#milesInput').value=state.miles[dateKey()]??''}
function renderProgress(){const o=calcOverall();$('#bigScoreValue').textContent=o+'%';$('#bigScoreLabel').textContent=labelFor(o);$('#bigScoreRing').style.background=`conic-gradient(${colorFor(o)} ${o*3.6}deg,#e1e8e3 0)`;const w=$('#categoryBars');w.innerHTML='';categories.forEach(c=>{const p=calcCategory(c);const row=document.createElement('div');row.className='category-row';row.innerHTML=`<strong>${c}</strong><div class="category-track"><div class="category-fill" style="width:${p}%;background:${colorFor(p)}"></div></div><b style="color:${colorFor(p)}">${p}%</b>`;w.appendChild(row)})}
function currentProjected(targetCats){const d=Object.assign({},ensureDay());targetCats.forEach(c=>d[c]='target');let total=0,den=0;categories.forEach(c=>{if(d[c]==='outside')return;den++;total+=d[c]==='target'?100:d[c]==='minimum'?80:0});return den?Math.round(total/den):0}
function renderPath(){const current=calcDay();const missing=categories.filter(c=>!ensureDay()[c]);let core=missing.slice(0,Math.max(1,Math.ceil(missing.length*.8)));let extra=missing;let items=[], projected=current,time='~10–20 min',summary='';if(mode==='protect'){items=missing.slice(0,3).map(c=>({c,label:state.goals[c].minimum,desc:`${c} minimum win`}));projected=Math.max(current,currentProjected([]));time='~10–20 min';summary='PROGRESS. NOT PERFECTION. Keep the habit alive with minimum wins.'}
else if(mode==='path'){items=core.map(c=>({c,label:state.goals[c].target,desc:`Complete ${c} target`}));projected=currentProjected(core);time='~20–40 min';summary='Take the shortest realistic route to the 80 line.'}
else{items=extra.map(c=>({c,label:state.goals[c].target,desc:`Complete ${c} target`}));items.push({c:'Fitness',label:'Optional strength or pickleball',desc:'Bank movement without affecting the 100-mile total'});projected=Math.max(currentProjected(extra),currentProjected(core));time='~45–90 min';summary='Complete the core path first, then use extra capacity to bank progress.'}
$('#pathPlanTitle').textContent=mode==='beyond'?'Go Beyond':mode==='protect'?'Protect the Habit':'Show Me The Path';$('#pathPlanSummary').textContent=summary;$('#pathTimeChip').textContent=time;$('#pathProjection').textContent=`Projected consistency: ${projected}% · ${labelFor(projected)}.`;const list=$('#pathActionList');list.innerHTML='';items.forEach(it=>{const l=document.createElement('label');l.className='path-action';l.innerHTML=`<input type="checkbox"><span><strong>${esc(it.label)}</strong><small>${esc(it.desc)}</small></span>`;list.appendChild(l)})}
function renderReview(){const counts={};for(const byCat of Object.values(state.why)){for(const arr of Object.values(byCat)){for(const r of arr)counts[r]=(counts[r]||0)+1}}const w=$('#whySummary');w.innerHTML='';const entries=Object.entries(counts).sort((a,b)=>b[1]-a[1]);if(!entries.length){w.innerHTML='<div class="why-summary-item"><strong>No WHY patterns yet.</strong><div class="muted">That’s okay. Context will build as you use the app.</div></div>';return}entries.forEach(([r,n])=>{const d=document.createElement('div');d.className='why-summary-item';d.innerHTML=`<strong>${esc(r)}</strong><div class="muted">Logged ${n} time${n===1?'':'s'} across individual commitments.</div>`;w.appendChild(d)})}
function renderGoals(){const w=$('#goalEditors');w.innerHTML='';categories.forEach(cat=>{const g=state.goals[cat]||defaultGoals[cat];const d=document.createElement('div');d.className='goal-editor';d.innerHTML=`<h3>${cat}</h3><label>Goal name<input data-f="name" value="${attr(g.name)}"></label><label>Target<input data-f="target" value="${attr(g.target)}"></label><label>Minimum<input data-f="minimum" value="${attr(g.minimum)}"></label>`;d.querySelectorAll('input').forEach(inp=>inp.onchange=()=>{state.goals[cat]??={};state.goals[cat][inp.dataset.f]=inp.value;save();renderHome();renderPath()});w.appendChild(d)})}
function renderAll(){renderHome();renderProgress();renderPath();renderReview();renderGoals()}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function attr(s){return esc(s)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
$$('.nav-btn').forEach(b=>b.onclick=()=>{const n=b.dataset.nav;$$('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===n));$$('.nav-btn').forEach(x=>x.classList.toggle('active',x===b));window.scrollTo({top:0,behavior:'smooth'})});
$('#prevDateBtn').onclick=()=>{selectedDay=Math.max(1,selectedDay-1);renderAll()};$('#nextDateBtn').onclick=()=>{selectedDay=Math.min(31,selectedDay+1);renderAll()};$('#saveMilesBtn').onclick=()=>{const v=Math.max(0,Number($('#milesInput').value)||0);state.miles[dateKey()]=v;save();renderMiles();toast('Mileage saved')};
$$('.mode-card').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;$$('.mode-card').forEach(x=>x.classList.toggle('selected',x===b));renderPath()});$('#reviewToPathBtn').onclick=()=>{$$('.nav-btn').find(b=>b.dataset.nav==='path').click()};
$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='the-eighty-backup.json';a.click();URL.revokeObjectURL(a.href)};$('#importInput').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{state=JSON.parse(await f.text());save();renderAll();toast('Backup imported')}catch{toast('Could not import backup')}};
$('#fitnessScreenshotInput').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;const status=$('#ocrStatus');status.classList.remove('hidden');status.textContent='Reading screenshot…';let text='';try{if(window.Tesseract){const r=await Tesseract.recognize(f,'eng',{logger:m=>{if(m.status==='recognizing text')status.textContent=`Reading screenshot… ${Math.round((m.progress||0)*100)}%`}});text=r.data.text||''}else throw new Error('OCR unavailable');const parsed=parseWorkout(text);$('#ocrActivity').value=parsed.activity;$('#ocrMiles').value=parsed.miles||'';$('#ocrDate').value=parsed.date;$('#ocrConfirm').classList.remove('hidden');status.textContent=parsed.miles?'Workout found. Confirm the details below.':'I could not confidently find mileage. Please confirm manually.'}catch{status.textContent='Auto-read is unavailable right now. Enter the details manually below.';$('#ocrConfirm').classList.remove('hidden');$('#ocrDate').value=dateKey()}};
function parseWorkout(text){const cleaned=text.replace(/\s+/g,' ');let activity=/Outdoor Run/i.test(cleaned)?'Outdoor Run':/Outdoor Walk/i.test(cleaned)?'Outdoor Walk':'Walk / Run';const mm=cleaned.match(/(?:Distance\s*)?(\d{1,2}(?:\.\d{1,2})?)\s*(?:MI|MILES)/i);let date=dateKey();const md=cleaned.match(/(?:Mon|Tue|Wed|Thu|Fri|Sat|Sun)[,\s]+(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+(\d{1,2})/i);if(md){const months={Jan:1,Feb:2,Mar:3,Apr:4,May:5,Jun:6,Jul:7,Aug:8,Sep:9,Oct:10,Nov:11,Dec:12};date=`2026-${String(months[md[1].slice(0,3)]).padStart(2,'0')}-${String(+md[2]).padStart(2,'0')}`}return{activity,miles:mm?+mm[1]:null,date}}
$('#confirmOcrBtn').onclick=()=>{const act=$('#ocrActivity').value.toLowerCase(),m=Number($('#ocrMiles').value),d=$('#ocrDate').value;if(!/walk|run/.test(act)){toast('Only walk/run mileage counts');return}if(!d||!(m>=0)){toast('Confirm date and mileage');return}state.miles[d]=(Number(state.miles[d])||0)+m;save();renderMiles();toast(`${m.toFixed(2)} miles added`);$('#ocrConfirm').classList.add('hidden')};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));renderAll();
})();
